// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace MBI_Calculator_Test_Project
{
    [TestFixture]
    public class CorrectInputTestSuiteChromeTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void normalWeightInputTest()
        {
            // Test name: normal_weight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 70
            driver.FindElement(By.Id("kg")).SendKeys("70");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter td | 
            driver.FindElement(By.CssSelector(".colcenter td")).Click();
            // 9 | assertValue | id=yourbmi | 24.2
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("24.2"));
            }
            // 10 | close |  | 
            driver.Close();
        }
        [Test]
        public void obeseInputTest()
        {
            // Test name: obese_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 100
            driver.FindElement(By.Id("kg")).SendKeys("100");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter div | 
            driver.FindElement(By.CssSelector(".colcenter div")).Click();
            // 9 | assertValue | id=yourbmi | 34.6
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("34.6"));
            }
            // 10 | close |  | 
            driver.Close();
        }
        [Test]
        public void overweightInputTest()
        {
            // Test name: overweight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | type | id=kg | 80
            driver.FindElement(By.Id("kg")).SendKeys("80");
            // 6 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 7 | click | id=yourbmi | 
            driver.FindElement(By.Id("yourbmi")).Click();
            // 8 | assertValue | id=yourbmi | 27.7
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("27.7"));
            }
            // 9 | close |  | 
            driver.Close();
        }
        [Test]
        public void underWeightInputTest()
        {
            // Test name: underweight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 45
            driver.FindElement(By.Id("kg")).SendKeys("45");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter td | 
            driver.FindElement(By.CssSelector(".colcenter td")).Click();
            // 9 | assertValue | id=yourbmi | 15.6
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("15.6"));
            }
            // 10 | close |  | 
            driver.Close();
        }
    }


    [TestFixture]
    public class CorrectInputTestSuiteFirefoxTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void normalWeightInputTest()
        {
            // Test name: normal_weight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 70
            driver.FindElement(By.Id("kg")).SendKeys("70");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter td | 
            driver.FindElement(By.CssSelector(".colcenter td")).Click();
            // 9 | assertValue | id=yourbmi | 24.2
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("24.2"));
            }
            // 10 | close |  | 
            driver.Close();
        }
        [Test]
        public void obeseInputTest()
        {
            // Test name: obese_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 100
            driver.FindElement(By.Id("kg")).SendKeys("100");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter div | 
            driver.FindElement(By.CssSelector(".colcenter div")).Click();
            // 9 | assertValue | id=yourbmi | 34.6
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("34.6"));
            }
            // 10 | close |  | 
            driver.Close();
        }
        [Test]
        public void overweightInputTest()
        {
            // Test name: overweight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | type | id=kg | 80
            driver.FindElement(By.Id("kg")).SendKeys("80");
            // 6 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 7 | click | id=yourbmi | 
            driver.FindElement(By.Id("yourbmi")).Click();
            // 8 | assertValue | id=yourbmi | 27.7
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("27.7"));
            }
            // 9 | close |  | 
            driver.Close();
        }
        [Test]
        public void underWeightInputTest()
        {
            // Test name: underweight_input_test
            // Step # | name | target | value
            // 1 | open | /health/educational/lose_wt/BMI/bmi-m.htm | 
            driver.Navigate().GoToUrl("https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi-m.htm");
            // 2 | setWindowSize | 915x1030 | 
            driver.Manage().Window.Size = new System.Drawing.Size(915, 1030);
            // 3 | click | id=htc | 
            driver.FindElement(By.Id("htc")).Click();
            // 4 | type | id=htc | 170
            driver.FindElement(By.Id("htc")).SendKeys("170");
            // 5 | click | id=kg | 
            driver.FindElement(By.Id("kg")).Click();
            // 6 | type | id=kg | 45
            driver.FindElement(By.Id("kg")).SendKeys("45");
            // 7 | click | css=.colcenter > input | 
            driver.FindElement(By.CssSelector(".colcenter > input")).Click();
            // 8 | click | css=.colcenter td | 
            driver.FindElement(By.CssSelector(".colcenter td")).Click();
            // 9 | assertValue | id=yourbmi | 15.6
            {
                string value = driver.FindElement(By.Id("yourbmi")).GetAttribute("value");
                Assert.That(value, Is.EqualTo("15.6"));
            }
            // 10 | close |  | 
            driver.Close();
        }
    }

}
